//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCE
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bancoSCE : DbContext
    {
        public bancoSCE()
            : base("name=bancoSCE")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<usuario> usuario { get; set; }
        public DbSet<fornecedor> fornecedor { get; set; }
        public DbSet<produto> produto { get; set; }
        public DbSet<listafornecedores> listafornecedores { get; set; }
        public DbSet<categoria> categoria { get; set; }
        public DbSet<pedidos> pedidos { get; set; }
        public DbSet<pedidosdetalhes> pedidosdetalhes { get; set; }
    }
}
