//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCE
{
    using System;
    using System.Collections.Generic;
    
    public partial class categoria
    {
        public int ID { get; set; }
        public string descricao { get; set; }
        public string ativo { get; set; }
    }
}
