//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCE
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedidosdetalhes
    {
        public int ID { get; set; }
        public int pedidoID { get; set; }
        public Nullable<int> produtoID { get; set; }
        public Nullable<int> quantidade { get; set; }
        public Nullable<double> custo { get; set; }
    
        public virtual pedidos pedidos { get; set; }
    }
}
