//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCE
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedidos
    {
        public pedidos()
        {
            this.pedidosdetalhes = new HashSet<pedidosdetalhes>();
        }
    
        public int ID { get; set; }
        public System.DateTime data { get; set; }
        public string usuario { get; set; }
        public string tipo { get; set; }
    
        public virtual ICollection<pedidosdetalhes> pedidosdetalhes { get; set; }
    }
}
